version: '2'
services:
  safh-app:
    image: safh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://safh-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=safh
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://safh-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://safh-elasticsearch:9200
    ports:
      - 8080:8080
  safh-mongodb:
    extends:
      file: mongodb.yml
      service: safh-mongodb
  safh-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: safh-elasticsearch
