version: '2'
services:
  safh-app:
    image: safh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://safh-postgresql:5432/safh
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://safh-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://safh-elasticsearch:9200
    ports:
      - 8080:8080
  safh-postgresql:
    extends:
      file: postgresql.yml
      service: safh-postgresql
  safh-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: safh-elasticsearch
