version: '2'
services:
    safh-app:
        image: safh
        external_links:
            - safh-postgresql:postgresql
            - safh-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/safh
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    safh-postgresql:
        extends:
            file: postgresql.yml
            service: safh-postgresql
    safh-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: safh-elasticsearch
