version: '2'
services:
  safh-app:
    image: safh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://safh-mysql:3306/safh?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://safh-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://safh-elasticsearch:9200
    ports:
      - 8080:8080
  safh-mysql:
    extends:
      file: mysql.yml
      service: safh-mysql
  safh-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: safh-elasticsearch
